// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnFDACusP56fTGTV2qoQAfX3VIDt10BA8',
    appId: '1:778303398420:web:e8f3106c92ea89253dbd01',
    messagingSenderId: '778303398420',
    projectId: 'filamentos-2a6cf',
    authDomain: 'filamentos-2a6cf.firebaseapp.com',
    storageBucket: 'filamentos-2a6cf.firebasestorage.app',
    measurementId: 'G-9R24ESDTXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98oHY9dGMkPu1I-sxpOpeefccXrJLJ2c',
    appId: '1:778303398420:android:3b31c9753538d4d43dbd01',
    messagingSenderId: '778303398420',
    projectId: 'filamentos-2a6cf',
    storageBucket: 'filamentos-2a6cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA23Ma3aUjjrO52eAX1OJpQtXyC_M_ou48',
    appId: '1:778303398420:ios:3ac2453d42adda903dbd01',
    messagingSenderId: '778303398420',
    projectId: 'filamentos-2a6cf',
    storageBucket: 'filamentos-2a6cf.firebasestorage.app',
    iosBundleId: 'com.example.sdeProjeto1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA23Ma3aUjjrO52eAX1OJpQtXyC_M_ou48',
    appId: '1:778303398420:ios:3ac2453d42adda903dbd01',
    messagingSenderId: '778303398420',
    projectId: 'filamentos-2a6cf',
    storageBucket: 'filamentos-2a6cf.firebasestorage.app',
    iosBundleId: 'com.example.sdeProjeto1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnFDACusP56fTGTV2qoQAfX3VIDt10BA8',
    appId: '1:778303398420:web:bd92a47781a0f46e3dbd01',
    messagingSenderId: '778303398420',
    projectId: 'filamentos-2a6cf',
    authDomain: 'filamentos-2a6cf.firebaseapp.com',
    storageBucket: 'filamentos-2a6cf.firebasestorage.app',
    measurementId: 'G-Y04FD6MGC9',
  );
}
